[project]
name = "discrete-mint-package"
authors = ["Discrete Labs"]
description = "A decentralized goal tracking and incentive system"
telemetry = false
requirements = []
[contracts.tracker]
path = "contracts/tracker.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
